#!/bin/sh
#
# Proposito do Script: Enable telnet from extension number from a list!
# Criado por Pedro Rodrigues
#                     ^ ^
#                   ( O O )
#   +============oOO==(_)==OOo==============+
#   | Pedro Rodrigues                       |
#   | phsr2001@gmail.com                    |
#   | pedro.rodrigues@3corp.com.br          |
#   +=======================================+

CommandScript(){
    while read extension; do
		/usr2/oneshot/mtcl/tool ippstat telnet d $extension t 1440 | paste -sd ' - ' > command
		archive=$(cat /DHS3bin/mtcl/scripts/command) 
		echo "$extension - $archive" >> result.log
	done < list_extension
	rm command
}		
CommandScript
